logging:
  level:
    root: INFO

server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/alfa_battle
    username: alfa_battle
    password: qwe123
    hikari:
      minimum-idle: 10
#  jpa:
#    hibernate:
#      ddl-auto: update